[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci --omit=dev --no-cache --prefer-offline",
  "npm cache clean --force"
]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "npm run railway:start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
